/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/ProjectName.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['3D_Text_-_K'].geometry} material={materials['Country Summer']} position={[-2, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_w'].geometry} material={materials['Country Summer']} position={[-1.5, 0,0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_a'].geometry} material={materials['Country Summer']} position={[-1, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_n'].geometry} material={materials['Country Summer']} position={[-0.5, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_g'].geometry} material={materials['Country Summer']} position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_y'].geometry} material={materials['Country Summer']} position={[0.5, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_o'].geometry} material={materials['Country Summer']} position={[1, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_u'].geometry} material={materials['Country Summer']} position={[1.5, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_l'].geometry} material={materials['Country Summer']} position={[2, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_S'].geometry} material={materials['Country Summer']} position={[-1.5, -0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_a'].geometry} material={materials['Country Summer']} position={[-1, -0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_g'].geometry} material={materials['Country Summer']} position={[-0.5, -0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_o'].geometry} material={materials['Country Summer']} position={[0, -0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_n'].geometry} material={materials['Country Summer']} position={[0.5, -0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes['3D_Text_-_g'].geometry} material={materials['Country Summer']} position={[1, -0.5, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/ProjectName.gltf')
